# Inserts a blank line between shell prompts
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

format = "$all"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
disabled = false

[time]
disabled = false

# Which is equivalent to
#format = """
#$username\
#$hostname\
#$shlvl\
#$kubernetes\
#$directory\
#$vcsh\
#$git_branch\
#$git_commit\
#$git_state\
#$git_status\
#$hg_branch\
#$docker_context\
#$package\
#$cmake\
#$dart\
#$deno\
#$dotnet\
#$elixir\
#$elm\
#$erlang\
#$golang\
#$helm\
#$java\
#$julia\
#$kotlin\
#$nim\
#$nodejs\
#$ocaml\
#$perl\
#$php\
#$purescript\
#$python\
#$red\
#$ruby\
#$rust\
#$scala\
#$swift\
#$terraform\
#$vlang\
#$vagrant\
#$zig\
#$nix_shell\
#$conda\
#$memory_usage\
#$aws\
#$gcloud\
#$openstack\
#$env_var\
#$crystal\
#$custom\
#$cmd_duration\
#$line_break\
#$lua\
#$jobs\
#$battery\
#$time\
#$status\
#$shell\
#$character"""

